// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm0vmEuHm2Hk8cAirqM85-BYLOHve89Qs',
    appId: '1:203394328510:web:eaa83c389357b02a817bef',
    messagingSenderId: '203394328510',
    projectId: 'my-moviebookingapp',
    authDomain: 'my-moviebookingapp.firebaseapp.com',
    databaseURL: 'https://my-moviebookingapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-moviebookingapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-e-1tlasxc-p8StOoYcIj84KJ01VC_LQ',
    appId: '1:203394328510:android:7ed784a54753c841817bef',
    messagingSenderId: '203394328510',
    projectId: 'my-moviebookingapp',
    databaseURL: 'https://my-moviebookingapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-moviebookingapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfKiZrv4KiVvytXKbkOWqdyJ2cT9lqr4Q',
    appId: '1:203394328510:ios:8797574b67b01371817bef',
    messagingSenderId: '203394328510',
    projectId: 'my-moviebookingapp',
    databaseURL: 'https://my-moviebookingapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-moviebookingapp.appspot.com',
    iosBundleId: 'com.example.moviebookingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfKiZrv4KiVvytXKbkOWqdyJ2cT9lqr4Q',
    appId: '1:203394328510:ios:8797574b67b01371817bef',
    messagingSenderId: '203394328510',
    projectId: 'my-moviebookingapp',
    databaseURL: 'https://my-moviebookingapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-moviebookingapp.appspot.com',
    iosBundleId: 'com.example.moviebookingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm0vmEuHm2Hk8cAirqM85-BYLOHve89Qs',
    appId: '1:203394328510:web:143a0a0d4bfd4a2d817bef',
    messagingSenderId: '203394328510',
    projectId: 'my-moviebookingapp',
    authDomain: 'my-moviebookingapp.firebaseapp.com',
    databaseURL: 'https://my-moviebookingapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-moviebookingapp.appspot.com',
  );

}